### PR TITLE
added the ability to set  and  using environment variables. Added exa…

### LINKED ISSUE #15: support for env variable based metadata
Hey all, just stumbled on this project and I LOVE it so far. 

I use a the docker based `amazon/dynamodb-local:latest` image for local testing and deploy tables into AWS with cdk, which makes the tables names variable based on the deployment.  

When testing locally, I have to change the model to set `__table_host__` and `__table_region__` to the local ddb instance, and remember to remove that before commit/deploy. 

And for the `__table_name__`,  I currently have to hard code the table name in cdk so that it matches the model definition. I'd rather use the dynamically generated table names and then set that as an ENV Variable on my lambdas/containers. 

I think it would be great if these props be set natively using environment variables, rather than hard coded in the models. That way they would be easy to over-ride for local testing/unit tests and could be dynamically set when deployed to AWS. 

If you are in support of this idea, I'll create a PR to implement.

### PR DESCRIPTION
**Pull request by peterb154**
…mple of dynamic  in readme fixed #15

### CODE REVIEW

**Comment by nayaverdier** [comment]
@peterb154 Thanks for the PR! I think it might be preferred to only lookup the environment variables if the value is not specified on the class, to avoid unexpected behavior during development. Setting a value on code seems "stronger" to me than setting an environment variables 

In most cases, either the production version will define the environment variables instead of hard coding, or even more common is not needing to specify the host, so the field is never set and setting the env var locally will override it as desired.

I'll add in support to set those with a callable as well before releasing, to make it more flexible for more complex usages.

Also, it might be useful to add a test to ensure the priority of the field vs environment variables (for whichever priority we land on).

**Comment by peterb154** [comment]
> @peterb154 Thanks for the PR! I think it might be preferred to only lookup the environment variables if the value is not specified on the class, to avoid unexpected behavior during development. Setting a value on code seems "stronger" to me than setting an environment variables

Obviously, this is your project, and giving preference to hard coded __table_host__ and __table_region__ makes sense I guess, especially when a dev will probably use *one* of the two, not both. 

> 
> In most cases, either the production version will define the environment variables instead of hard coding, or even more common is not needing to specify the host, so the field is never set and setting the env var locally will override it as desired.

In production, I would say that typically no meta or env vars for table and region will be defined, as users will apps be using the default host and region setter provided in the aws client/resource/session etc. 

> 
> I'll add in support to set those with a callable as well before releasing, to make it more flexible for more complex usages.
> 
> Also, it might be useful to add a test to ensure the priority of the field vs environment variables (for whichever priority we land on).

Sure. If you want me to re-work the pr, I can do that. Or you can fine tune it to your preferences from here. No problem either way.

**Comment by nayaverdier** [comment]
Feel free to make the changes if you want, I'm out of town and won't have access to my computer until later in the week. Otherwise I'll make the tweaks when I'm back, either way.

**Comment by peterb154** [comment]
@nayaverdier I just updated the PR to 
1. Prioritize `__table__host__` over env var `DYNATISTIC_HOST` with tests to prove working
2. Prioritize `__table__region__` over env var `DYNATISTIC_REGION` with tests to prove working
3. Allow `__table__host__` & `__table__region__` to be callables with tests to prove working
5. updated Readme to reflect these changes

**Comment by nayaverdier** [comment]
Looks great, thanks for the changes! I just did a small refactor to isolate the resolution of the fields vs assignment. Will merge and deploy shortly.

**Pull request merged**
